# Generated by Django 4.2.5 on 2023-10-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_tb',
            new_name='register',
        ),
    ]
