# Generated by Django 4.2.5 on 2023-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_register_tb_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='usertype',
            field=models.IntegerField(default=2),
        ),
    ]
