# Generated by Django 4.2.5 on 2023-10-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_delivery_agent_product_suppliers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_agent',
            name='id',
        ),
    ]
