# Generated by Django 4.2.5 on 2023-10-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_register_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
    ]
