# Generated by Django 4.2.5 on 2023-10-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_agent',
            name='status',
        ),
    ]
