# Generated by Django 4.2.5 on 2023-10-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_delivery_agent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
