# Generated by Django 4.2.5 on 2023-10-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.suppliers'),
            preserve_default=False,
        ),
    ]
