# Generated by Django 4.2.5 on 2023-10-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone_no',
            field=models.CharField(default='9895674532', max_length=100),
        ),
    ]
