# Generated by Django 4.2.5 on 2023-10-16 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_register_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='qty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('cart_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart_items')),
            ],
        ),
    ]
