# Generated by Django 4.2.5 on 2023-10-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cart_items_qty_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
