# Generated by Django 4.2.5 on 2023-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_agent',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='agent_id/'),
        ),
    ]
