# Generated by Django 4.2.5 on 2023-10-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delivery_agent_id_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='deliver_status',
        ),
        migrations.AddField(
            model_name='orders',
            name='pickup_status',
            field=models.BooleanField(default=False),
        ),
    ]
