# Generated by Django 4.2.5 on 2023-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_status_orders_deliver_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_agent',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
