# Generated by Django 4.2.5 on 2023-10-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_orders_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.register'),
            preserve_default=False,
        ),
    ]
