# Generated by Django 4.2.5 on 2023-10-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_orders_cart_id_orders_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='agents_id',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='app.delivery_agent'),
            preserve_default=False,
        ),
    ]
