# Generated by Django 4.2.5 on 2023-10-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_orders_agents_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='phone_no',
            field=models.CharField(default='9895674532', max_length=100),
        ),
    ]
